# Generated by Django 4.1.7 on 2023-03-01 07:16

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupant',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Room_x_Occupant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('inRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.room')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.occupant')),
            ],
        ),
        migrations.CreateModel(
            name='Occupant_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='attendance.occupant')),
            ],
        ),
        migrations.CreateModel(
            name='Occupant_Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('img', models.ImageField(default=None, upload_to='images/')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('occupant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picture', to='attendance.occupant')),
            ],
        ),
    ]
