# Generated by Django 4.1.8 on 2023-04-18 12:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_occupant_picture_imagetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupant_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(default=uuid.uuid4, editable=False, max_length=36)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.installation')),
            ],
        ),
    ]
