# Generated by Django 4.1.8 on 2023-04-18 12:45

from django.db import migrations
from django.contrib.sites.models import Site
from django.conf import settings

def add_default_site(apps, schema_editor):

    default_site = Site(domain=settings.DEFAULT_DOMAIN, id=23, name="default domain")
    default_site.save()

class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_occupant_type'),
        ('sites', '0002_alter_domain_unique')
    ]

    operations = [
        migrations.RunPython(add_default_site)
    ]
