# Generated by Django 4.1.9 on 2023-07-16 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_add_default_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='occupant',
            name='installation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendance.installation'),
            preserve_default=False,
        ),
    ]
